schema_version: 20180708
name: twitterlist
version: 0.0.41
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: twitterlist-trigger
  type: http
  source: /twitterlist-trigger
