schema_version: 20180708
name: twitter-follow
version: 0.0.6
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: twitter-follow-trigger
  type: http
  source: /twitter-follow-trigger
