schema_version: 20180708
name: twitter-filter-follow
version: 0.0.4
runtime: node
entrypoint: node func.js
format: http-stream
triggers:
- name: twitter-filter-follow-trigger
  type: http
  source: /twitter-filter-follow-trigger
